name: Dev branch workflow - Test and check thing

on:
  # Runs on opened pull request targeting the dev branch
  # When I want to merge feature branch into dev branch
  pull_request:
    types:
      - opened
    branches:
      - dev
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Testing jobs in dev branch
  test_dev_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Call testing reusable workflow
        uses: ./test.workflow.yml
