name: Dev Workflow - Test and check thing

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - dev
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Testing jobs
  test:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4.1.1

      # - name: Setup Node
      #   uses: actions/setup-node@v4.0.1
      #   with:
      #     node-version: 20.10.0
      #     cache: npm

      # - name: Install dependencies
      #   run: npm ci

      - name: Run e2e test
        run: echo "Hello test"

      # - name: Build project
      #   run: npm run build

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: ./next
      
  # Merging/Pull request job ?
  # merge:
  #   runs-on: ubuntu-latest

  #   needs: test

  #   steps:
  #     - name: Download artifact
  #       use: actions/download-artifact@v4
  #       with:
  #         path: ./next

  #     - name: Start production project
  #       run: npm run start

  #     - name: Connect to vps & run docker
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         script: docker compose up -d --build
