name: Main branch workflow - Test and check thing

on:
  # Runs on opened pull request targeting the main branch
  # When I want to merge dev branch into main branch
  pull_request:
    types:
      - opened
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Testing jobs in main branch
  test_main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Call testing reusable workflow
        uses: ./test.workflow.yml
