name: Prod Workflow - Build and deploy to production

on:
  # Runs on closed pull request targeting the main branch
  pull_request:
    types:
      - closed
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build jobs
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to actions
        run: echo "Hello actions"


    #   - name: Checkout code
    #     uses: actions/checkout@v4.1.1

      # - name: Setup Node
      #   uses: actions/setup-node@v4.0.1
      #   with:
      #     node-version: 20.10.0
      #     cache: npm

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build project
      #   run: npm run build

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: ./next
      
  # Deployment job
  # deploy:
  #   runs-on: ubuntu-latest

    # needs: build

    # steps:
    # - name: Download artifact
    #   use: actions/download-artifact@v4
    #   with:
    #     path: ./next

    # - name: Start production project
    #   run: npm run start

    # - name: Connect to vps & run docker
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     script: docker compose up -d --build
